# Generated by Django 5.0.6 on 2025-05-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_white', models.CharField(blank=True, max_length=255)),
                ('title_red', models.CharField(blank=True, max_length=255)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('what_do', models.TextField(blank=True)),
                ('Why_Choose_Softvence', models.TextField(blank=True)),
                ('our_misson', models.TextField(blank=True)),
                ('count_01_title', models.CharField(blank=True, max_length=255)),
                ('count_01', models.IntegerField(default=0)),
                ('count_02_title', models.CharField(blank=True, max_length=255)),
                ('count_02', models.IntegerField(default=0)),
                ('button_text', models.CharField(blank=True, max_length=255)),
                ('button_url', models.URLField(blank=True)),
                ('team_section_title_1', models.CharField(blank=True, max_length=255)),
                ('team_section_title_2', models.CharField(blank=True, max_length=255)),
                ('testimonial_section_title_1', models.CharField(blank=True, max_length=255)),
                ('testimonial_section_title_2', models.CharField(blank=True, max_length=255)),
                ('client_section_title_1', models.CharField(blank=True, max_length=255)),
                ('client_section_title_2', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('call_us', models.IntegerField(blank=True, null=True)),
                ('mail', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('map', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='FontAwesome icon class (e.g., fa-solid fa-code)', max_length=100)),
            ],
        ),
    ]
