# Generated by Django 5.0.6 on 2025-05-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrmsettings',
            name='clock_in_max_time',
            field=models.TimeField(default='09:00:00', verbose_name='HRM Attendance Clock In Max Time'),
        ),
        migrations.AlterField(
            model_name='hrmsettings',
            name='clock_out_min_time',
            field=models.TimeField(default='17:00:00', verbose_name='HRM Attendance Clock Out Min Time'),
        ),
    ]
