# Generated by Django 5.0.6 on 2025-05-21 18:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_hrmsettings_clock_in_max_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBottom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_text', models.TextField(verbose_name='Small Text (Under Logo)')),
                ('first_column_title', models.CharField(max_length=100)),
                ('first_column_choice', models.CharField(max_length=100)),
                ('first_column_description', ckeditor.fields.RichTextField(help_text='Use <ul> and <li> tags')),
                ('second_column_title', models.CharField(max_length=100)),
                ('second_column_description', ckeditor.fields.RichTextField(help_text='Use <ul> and <li> tags')),
                ('third_column_title', models.CharField(max_length=100)),
                ('third_column_description', ckeditor.fields.RichTextField(help_text='Use <ul> and <li> tags')),
            ],
        ),
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content_choice', models.CharField(blank=True, max_length=100, null=True)),
                ('description', ckeditor.fields.RichTextField(help_text='Use <ul> and <li> tags')),
            ],
            options={
                'verbose_name': 'Footer Column',
                'verbose_name_plural': 'Footer Columns',
            },
        ),
        migrations.CreateModel(
            name='FooterCopyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_text', models.CharField(max_length=100, verbose_name='Copyright Text')),
                ('privacy_policy', models.CharField(max_length=20, verbose_name='Privacy Policy Page Title')),
                ('terms_page', models.CharField(max_length=20, verbose_name='Terms Page Title')),
            ],
        ),
        migrations.CreateModel(
            name='FooterLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FooterTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('button_text', models.CharField(max_length=100)),
                ('button_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=150, verbose_name='Meta Title')),
                ('tag_line', models.CharField(max_length=150, verbose_name='Tag Line')),
                ('meta_description', models.TextField(verbose_name='Meta Description')),
                ('seo_keywords', models.TextField(help_text='Comma-separated keywords for SEO', verbose_name='SEO Keywords')),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='meta_images/', verbose_name='Meta Image')),
            ],
            options={
                'verbose_name': 'SEO Settings',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('pinterest', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('placeholder', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=50)),
            ],
        ),
    ]
