# Generated by Django 5.0.6 on 2025-05-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_footerbottom_footercolumn_footercopyright_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('sslcommerz', 'SSLCOMMERZ'), ('instamojo', 'Instamojo'), ('paymob', 'Paymob')], help_text='Select the payment gateway you want to configure.', max_length=50, verbose_name='Payment Gateway')),
                ('config', models.JSONField(default=dict, help_text='Enter key-value pairs for API credentials and settings (e.g., client_id, secret_key, etc.)', verbose_name='Configuration')),
                ('sandbox', models.BooleanField(default=False, help_text='Enable this to use test/sandbox credentials instead of live ones.', verbose_name='Sandbox Mode')),
                ('active', models.BooleanField(default=False, help_text='Enable this payment method for users.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
    ]
